name: concurrency
on: push
concurrency:
  group: mbapp
  cancel-in-progress: true
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: concurrencyy
        run: |
          echo "Today's date is::"
          date
          sleep 38