name: concurrency
on: push
concurrency:
  group: mbapp
  cancel-in-progress: false
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: concurrency
        run: |
          echo "Today's date:"
          date
          sleep 35
         
          
          
          
          