name: githubpackages
on: push
permissions:
    contents: read
    packages: write
jobs:
    job1:
      runs-on: ubuntu-latest
      steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: image build
        run: |
              docker build -t ghcr.io/${{ github.actor }}/myapp:latest .
              docker images
      - name: github push
        run: |
            docker login ghcr.io -u "${{ github.actor }}" -p "${{ secrets.GITHUB_TOKEN }}"
            docker push ghcr.io/${{ github.actor }}/myapp:latest
