name: workflow - 4
on: workflow_dispatch
jobs:
    linux-job:
     runs-on: ubuntu-latest
     steps: 
     - name:
       run: |
            pwd
            echo "This is test step"
     - name: checking docker version
       run:  docker info
    Linux-job1:
     needs: linux-job
     runs-on: ubuntu-latest
     steps:
     - name: display Date
       run: date
    windows-job:
     needs: [linux-job , Linux-job1]
     runs-on: windows-latest
     steps:
     - name: Display list of files
       run:  dir