name: secrets
on: workflow_dispatch
env:
  abc: ${{secrets.MYPASSWORD}}
jobs:
   job1:
      runs-on: ubuntu-latest
      steps:
      - name: secrets
        run: echo print secret 
            echo $abc